name: sitemarker
version: 3.1.0
summary: Sitemarker: The Ultimate Cross-Platform Bookmark Manager
description: |
  Take control of your digital life with Sitemarker, the intuitive and powerful bookmark manager designed for seamless cross-platform use. Whether you're on Windows, Linux, or macOS, Sitemarker keeps your favorite websites organized, accessible, and up-to-date.

  Key Features:

    Effortless Organization: Categorize and tag your bookmarks for quick retrieval. No more endless scrolling!
    Smart Search: Find any saved link in an instant with powerful, keyword-based search.
    Clean & Intuitive Interface: Enjoy a modern, clutter-free design that makes managing your bookmarks a breeze.
    Stay Updated: Keep your online resources fresh and relevant.
    Sitemarker simplifies how you interact with the web. Download now and redefine your Browse experience!


contact: https://github.com/aerocyber/sitemarker/issues
issues: https://github.com/aerocyber/sitemarker/issues
license: Apache-2.0
source-code: https://github.com/aerocyber/sitemarker
title: Sitemarker
website: https://aerocyber.github.io/sitemarker
confinement: strict
base: core24
platforms:
  amd64:
  arm64:

# grade: beta

# slots:
#  dbus-sitemarker:
#    interface: dbus
#    bus: session
#    name: io.github.aerocyber.sitemarker

apps:
  sitemarker:
    command: sitemarker
    extensions: [gnome]
    plugs:
      - network
      - home
 #   slots:
 #     - dbus-sitemarker

parts:
  sitemarker:
    build-packages:
      - curl
      - git
      - unzip
      - xz-utils
      - zip
      - libglu1-mesa
      - clang
      - make
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      - libstdc++-12-dev
    source: ./sitemarker
    plugin: flutter
    flutter-target: lib/main.dart
