name: sitemarker
version: 3.0.0
summary: Bookmarking made elegant
description: |
  Make sharing bookmarks easier using Sitemarker, the bookmark manager.
contact: https://github.com/aerocyber/sitemarker/issues
issues: https://github.com/aerocyber/sitemarker/issues
license: Apache-2.0
source-code: https://github.com/aerocyber/sitemarker
title: Sitemarker
website: https://aerocyber.github.io/sitemarker
confinement: strict
base: core24
platforms:
  amd64:
  arm64:

# grade: beta

# slots:
#  dbus-sitemarker:
#    interface: dbus
#    bus: session
#    name: io.github.aerocyber.sitemarker

apps:
  sitemarker:
    command: sitemarker
    extensions: [gnome]
    plugs:
      - network
      - home
 #   slots:
 #     - dbus-sitemarker

parts:
  sitemarker:
    build-packages:
      - curl
      - git
      - unzip
      - xz-utils
      - zip
      - libglu1-mesa
      - clang
      - make
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      - libstdc++-12-dev
    source: ./sitemarker
    plugin: flutter
    flutter-target: lib/main.dart
