name: sitemarker
version: 2.1.0
summary: Open source bookmark manager.
description: |
  Make sharing bookmarks easier using Osmata, the bookmark manager.

confinement: strict
base: core22
# grade: beta

# slots:
#  dbus-sitemarker:
#    interface: dbus
#    bus: session
#    name: io.github.aerocyber.sitemarker

apps:
  sitemarker:
    command: sitemarker
    extensions: [gnome]
    plugs:
      - network
      - home
 #   slots:
 #     - dbus-sitemarker

parts:
  sitemarker:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
