name: sitemarker
description: "An open source bookmark manager."

publish_to: 'none'

version: 3.1.0-10 # TODO: Update version number before release. Don't forget to bump the build number as well.
# 10 is the base for 3.x series as of 3.1.x
# Version 4.x will have base of 100
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.1
  path_provider: ^2.1.2
  path: ^1.9.0
  shared_preferences: ^2.3.4
  provider: ^6.1.1
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.20
  logger: ^2.1.0
  sqlite3: ^2.4.0
  http: ^1.2.2
  package_info_plus: ^8.0.0
  validators: ^3.0.0
  intl: ^0.20.1
  drift_flutter: ^0.2.2
  html: ^0.15.5
  file_picker: ^10.1.9
  receive_sharing_intent: ^1.8.1
  toastification: ^3.0.2
  crypto: ^3.0.6
  permission_handler: ^12.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.22.1
  test: ^1.25.7
  msix: ^3.16.9

flutter:
  uses-material-design: true

  assets:
    - assets/themes/
    - assets/io.github.aerocyber.sitemarker.png
