name: PR Build Check

on:
  push:
    branches:
      - main
      - stable
      - develop
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - synchronized
    branches:
      - main
      - develop
      - stable
  workflow_dispatch:

jobs:
  build_check_android:
    name: Check if Android APK build against the PR/Push is successful
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sitemarker

    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - name: Set up Java 17
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          log-accepted-android-sdk-licenses: false
          accept-android-sdk-licenses: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: sitemarker/pubspec.yaml
          cache: true

      - name: Get flutter project dependencies
        run: flutter pub get

      # TODO: Tests not ready :P
      # - name: Run flutter analyze
      #   run: flutter analyze

      - name: Run build_runner
        run: dart run build_runner build

      - name: Run Build steps for APK
        run: flutter build apk --release --flavor prod --shrink

  build_check_linux:
    name: Check if build for Linux against the PR/Push is Successful
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sitemarker

    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - name: Install necessary packages
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libstdc++-12-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: sitemarker/pubspec.yaml
          cache: true

      - name: Get flutter project dependencies
        run: flutter pub get

      # TODO: Tests not ready :P
      # - name: Run flutter analyze
      #   run: flutter analyze

      - name: Run build_runner
        run: dart run build_runner build

      - name: Run Build steps for linux
        run: flutter build linux --release

  build_check_windows:
    name: Check if build for Windows against the PR/Push is Successful
    runs-on: windows-latest

    defaults:
      run:
        working-directory: sitemarker

    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: sitemarker/pubspec.yaml
          cache: true

      - name: Get flutter project dependencies
        run: flutter pub get

      - name: Run build_runner
        run: dart run build_runner build

      # TODO: Tests not ready :P
      # - name: Run flutter analyze
      #   run: flutter analyze

      - name: Run Build steps for windows
        run: flutter build windows --release

  build_check_web:
    name: Check if build for Web (WASM) against the PR/Push is Successful
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sitemarker

    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: sitemarker/pubspec.yaml
          cache: true

      - name: Get flutter project dependencies
        run: flutter pub get

      - name: Run build_runner
        run: dart run build_runner build

      # TODO: Tests not ready :P
      # - name: Run flutter analyze
      #   run: flutter analyze

      - name: Run Build steps for web
        run: flutter build web --release --wasm
